MvcProjeKampi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AboutController : Controller
    {      

        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index()
        {
            var aboutvalues = abm.GetList();
            return View(aboutvalues);
        }

        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAbout(About p)
        {
            abm.AboutAdd(p);
            return RedirectToAction("Index");
        }

        public PartialViewResult AboutPartial()
        {
            return PartialView();
        }
    }
}

MvcProjeKampi/Views/About/AboutPartial.cshtml
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Yeni Hakkımızda Yazı Girişi
</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Hakkımızda Metin Girişi</h2>
            </div>
            <form method="post" action="/About/AddAbout/">
                <div class="modal-body">
                    <label>Hakkımda Metin 1</label>
                    <input type="text" name="AboutDetails1" class="form-control" />
                    <br />
                    <label>Hakkımda Metin 2</label>
                    <input type="text" name="AboutDetails2" class="form-control" />
                    <br />
                    <label>Hakkımda Görsel 1</label>
                    <input type="text" name="AboutImage1" class="form-control" />
                    <br />
                    <label>Hakkımda Görsel 2</label>
                    <input type="text" name="AboutImage2" class="form-control" />
                    <br />
                    <button class="btn btn-info">Kaydet</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                </div>
            </form>
        </div>
    </div>
</div>

MvcProjeKampi/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Hakkımda Veri Listesi</h2>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Hakkımda Detay 1</th>
        <th>Hakkımda Detay 2</th>
        <th>Hakkımda İmage 1</th>
        <th>Hakkımda İmage 2</th>
        <th>Aktif Yap</th>
        <th>Pasif Yap</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AboutID</td>
            <td>@item.AboutDetails1</td>
            <td>@item.AboutDetails2</td>
            <td>@item.AboutImage1</td>
            <td>@item.AboutImage2</td>
            <td><a href="#" class="btn btn-warning">Aktif Yap</a></td>
            <td><a href="#" class="btn btn-danger">Pasif Yap</a></td>
        </tr>
}
</table>


@Html.Action("AboutPartial", "About")