MvcProjeKampi/Controllers/ChartController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using MvcProjeKampi.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
namespace MvcProjeKampi.Controllers
{
    public class ChartController : Controller
    {     

        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        ContentManager cm = new ContentManager(new EfContentDal());

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CategoryChart()
        {
            return Json(BlogList(), JsonRequestBehavior.AllowGet);
        }
        public List<CategoryClass> BlogList()
        {
            List<CategoryClass> ct = new List<CategoryClass>();
            ct.Add(new CategoryClass()
            {
                CategoryName = "Yazılım",
                CategoryCount = 8
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Seyehat",
                CategoryCount = 4
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Teknoloji",
                CategoryCount = 7
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Spor",
                CategoryCount = 1
            });
            return ct;
        }
        public ActionResult HeadingChartIndex()
        {
            return View();
        }
        public ActionResult HeadingChart()
        {
            return Json(HeadingEntryList(), JsonRequestBehavior.AllowGet);
        }
        public List<HeadingClass> HeadingEntryList()
        {
            List<HeadingClass> headingClasses = new List<HeadingClass>();
            using (var Context = new Context())
            {
                headingClasses = Context.Headings.Select(x => new HeadingClass
                {
                    HeadingName = x.HeadingName,
                    ContentCount = x.Contents.Count()
                }).ToList();
            };
            return headingClasses;
        }        

        public ActionResult WriterHeadingIndex()
        {
            return View();
        }
        public ActionResult WriterHeadingChart()
        {
            return Json(WriterHeadingList(), JsonRequestBehavior.AllowGet);
        }
        public List<WriterHeadingCount> WriterHeadingList()
        {
            
            List<WriterHeadingCount> writerHeadingCounts = new List<WriterHeadingCount>();
            using (var Context = new Context())
            {
                writerHeadingCounts = Context.Writers.Select(x => new WriterHeadingCount
                {
                    WriterName = x.WriterName,
                    HeadingCount = x.Headings.Count()
                }).ToList();
            };
            return writerHeadingCounts;
        }
    }


}

MvcProjeKampi/Views/Chart/HeadingChartIndex.cshtml
@{
    ViewBag.Title = "HeadingChartIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Başlık Etkileşim Grafiği</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("HeadingChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'HeadingName');
            data.addColumn('number', 'ContentCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.HeadingName, obj.ContentCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Başlık - Entry Grafiği",
                width: 1280,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('Piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', 'CategoryCount');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Kategori - Blog Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/WriterHeadingIndex.cshtml
@{
    ViewBag.Title = "WriterHeadingIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("WriterHeadingChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'WriterName');
            data.addColumn('number', 'HeadingCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.WriterName, obj.HeadingCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Yazar - Açılan Başlık Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.LineChart(document
                .getElementById('Piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>